# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d590c722ef96e744790dc58a65e3f760217559095a8a1ab20f899757564cacfb6a1db0978df2eec1389224f28ab1c37fc7e73faa8e5340fa2dc947f766261907

test:
  secret_key_base: c6cb8aa0a883a6fc358603b5589bbce1e81e3b6734b3b0038ba6f15f292334aa60f7934a8c96711dd10aa60d49b4c2f8dc85a2faea78c586f640c4c4a02b7371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
